### ISSUE TITLE
Bug: Backdrop Missing on Some Bars

### ISSUE THREAD

**Issue by ArenfeIdt** [SFX-WoW/Masque#256]
### Game Flavor

Retail

### Game Version

10.0.0

### Add-On Version

10.0.0

### Description

Good Evening,

as of the new 10.0.0 Version of Masque the backdrop of certain Bars (Bartender4 - Stance Bar) and Skins (Elvuisque - Weakauras in this Instance) is no longer being displayed, using the 9.2.7 Version of Masque does display those Backdrops but it has the already known Scaling issues.

Best Regards

### Screenshots

![backdropmissing](https://user-images.githubusercontent.com/41451315/198392745-66f51c8d-7f77-4058-8ded-e5c5b7fd2fc5.png)

**Comment by StormFX** [comment]
Try Beta-2. I just released it.

**Comment by XeeLiao** [comment]
Screenshot was taken with Beta-2, did not fix it unfortunately

**Comment by StormFX** [comment]
I'll look into it.

**Comment by XeeLiao** [comment]
by the way, theres also this, dont know if this is something thats caused by masque but if i move my Bars up by 1 in Bartenders4 it becomes as shown here

![positioning](https://user-images.githubusercontent.com/41451315/198396118-d7e6b9e6-fb4a-4668-807d-cb8e4f56c5c2.png)

**Comment by StormFX** [comment]
Oops! I missed something. Change `Masque\Core\Regions\Backdrop.lua` Line 153 from

```lua
	if Enabled and not Skin.Hide and EmptyTypes[bType] then`
```

To

```lua
	if Enabled and not Skin.Hide then
```

**Comment by XeeLiao** [comment]
worked like a charm, thank you very much for the quick response


![backdropmissing](https://user-images.githubusercontent.com/41451315/198397860-b381269c-7726-4c28-9957-9b2fe69a4a23.png)

**Comment by StormFX** [comment]
No problem. I'll have it fixed in the next build.

**Comment by StormFX** [comment]
Fixed in 85cfd8d.
